dp_version_optimize
carlosegg/pipeline_plugin pull request #50
Opened 2021-04-16 21:04 UTC by carlosegg

2021-04-18 13:09 UTC, caenco requested changes

2021-04-18 13:09 UTC, caenco commented on plugin/app/plugins/pipeline_plugin/tools/versions/get_git_version_string.sh
> +             major_version=$(grep $(grep "refs/tags/${ko_version}" ${git_root_dir}/.git/packed-refs|awk '{print $1}') ${git_root_dir}/.git/packed-refs |grep -Po "(?<=refs/tags/).*(?=/KO)"|tail -1)
Creo que falta el KO
$(grep $(grep "refs/tags/${ko_version}/KO" ..... ¿no?

2021-04-18 13:09 UTC, caenco commented on plugin/app/plugins/pipeline_plugin/tools/versions/get_git_version_string.sh
> +    setCacheProperty 'cache_version_string'
Pero hay que hacer el echo igual, ¿no?

2021-04-18 13:09 UTC, caenco commented on plugin/app/plugins/pipeline_plugin/tools/versions/get_git_version_string.sh
> +{   getCacheProperty 'cache_version_string' && return 0
¿No hay que hacer el echo o algún return de ese cache_version_string?

2021-04-18 16:19 UTC, carlosegg commented on plugin/app/plugins/pipeline_plugin/tools/versions/get_git_version_string.sh
> +{   getCacheProperty 'cache_version_string' && return 0
No hace falta https://github.com/carlosegg/pipeline_plugin/blob/a099e1fa8b3ab52e5a03c6f5b1586e963dda6a32/plugin/app/plugins/pipeline_plugin/tools/versions/dp_version.sh#L5

2021-04-18 16:20 UTC, carlosegg commented on plugin/app/plugins/pipeline_plugin/tools/versions/get_git_version_string.sh
> +             major_version=$(grep $(grep "refs/tags/${ko_version}" ${git_root_dir}/.git/packed-refs|awk '{print $1}') ${git_root_dir}/.git/packed-refs |grep -Po "(?<=refs/tags/).*(?=/KO)"|tail -1)
Igualmente estaba salvado por la campana porque sólo tenemos KO, si hubisemos tenido CC si que la huberia liado
Peero ya lo he añadido.

2021-04-18 16:20 UTC, carlosegg commented on plugin/app/plugins/pipeline_plugin/tools/versions/get_git_version_string.sh
> +           major_version=$(grep $(grep "refs/tags/${ko_version}/KO" ${git_root_dir}/.git/packed-refs|awk '{print $1}') ${git_root_dir}/.git/packed-refs |grep -Po "(?<=refs/tags/).*(?=/KO)"|tail -1)
LLevabas razón , pero nos ha salvado que no hay otro tag tipo 8.2.0/CC

2021-04-19 09:01 UTC, caenco commented on plugin/app/plugins/pipeline_plugin/tools/versions/get_git_version_string.sh
> +           major_version=$(grep $(grep "refs/tags/${ko_version}/KO" ${git_root_dir}/.git/packed-refs|awk '{print $1}') ${git_root_dir}/.git/packed-refs |grep -Po "(?<=refs/tags/).*(?=/KO)"|tail -1)
Revisar

2021-04-19 10:55 UTC, merged